- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Creating a sample keypair
      ec2_key:
        name: sample_keypair
        region: us-east-2
      register: keyout
    - debug:
        var: keyout
    - name: Saving the pub key to a file
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample_key.pem
      when: keyout.changed