- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Include vpc variables
      include_vars:
        file: ./vars/vpc_vars

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_Cidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        tags:
          project: Vprofile
          author: VDM
        tenancy: dedicated
      register: vpcout

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub1