- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Include vpc variables
      include_vars:
        file: ./vars/vpc_vars

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_Cidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        dns_hostnames: yes
        tags:
          project: Vprofile
          author: VDM
        tenancy: default
      register: vpcout

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3
      ec2_vpc_subnet:
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub3
      register: pubsub3_out

    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub1
      register: privsub1_out

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub2
      register: privsub2_out

    - name: Create Private Subnet 3
      ec2_vpc_subnet:
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub3
      register: privsub3_out

    - name: Create Internet GateWay
      ec2_vpc_igw:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        tags:
          Name: Vprofile-IGW
      register: igwout

    - name: Create Pubic Subnet Route Table
      ec2_vpc_route_table:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igwout.gateway_id }}"
        tags:
          Name: Public_RT
      register: pubRT_out

    - name: Create NAT Gateway
      ec2_vpc_nat_gateway:
        region: "{{region}}"
        state: "{{state}}"
        if_exist_do_not_create: yes
        subnet_id: "{{pubsub1_out.subnet.id}}"
        wait: yes
      register: natGW_out

    - name: Create Private Subnet Route Table
      ec2_vpc_route_table:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        subnets:
          - "{{ privsub1_out.subnet.id }}"
          - "{{ privsub2_out.subnet.id }}"
          - "{{ privsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ natGW_out.nat_gateway_id }}"
        tags:
          Name: Private_RT
      register: privRT_out

    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igwout.gateway_id
        - pubRT_out.route_table.id
        - natGW_out.nat_gateway_id
        - privRT_out.route_table.id

    - set_fact:
        vpcid: "{{vpcout.vpc.id}}"
        pubsub1id: "{{pubsub1_out.subnet.id}}"
        pubsub2id: "{{pubsub2_out.subnet.id}}"
        pubsub3id: "{{pubsub3_out.subnet.id}}"
        privsub1id: "{{privsub1_out.subnet.id}}"
        privsub2id: "{{privsub2_out.subnet.id}}"
        privsub3id: "{{privsub3_out.subnet.id}}"
        igwid: "{{igwout.gateway_id}}"
        pubRTid: "{{pubRT_out.route_table.id}}"
        natgwid: "{{natGW_out.nat_gateway_id}}"
        privRTid: "{{privRT_out.route_table.id}}"
        cacheable: yes

    - name: Creating a variable file from vpc outputs
      copy:
        content: "vpcid: {{vpcout.vpc.id}}\npubsub1id: {{pubsub1_out.subnet.id}}\npubsub2id: {{pubsub2_out.subnet.id}}\npubsub3id: {{pubsub3_out.subnet.id}}\nprivsub1id: {{privsub1_out.subnet.id}}\nprivsub2id: {{privsub2_out.subnet.id}}\nprivsub3id: {{privsub3_out.subnet.id}}\nigwid: {{igwout.gateway_id}}\npubRTid: {{pubRT_out.route_table.id}}\nnatgwid: {{natGW_out.nat_gateway_id}}\nprivRTid: {{privRT_out.route_table.id}}\n"
        dest: ./vars/output_vars




