- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Include vpc variables
      include_vars:
        file: ./vars/vpc_vars

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_Cidr}}"
        region: "{{region}}"
        state: "{{state}}"
        dns_support: yes
        tags:
          project: Vprofile
          author: VDM
        tenancy: dedicated
      register: vpcout

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        cidr: "{{PubSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub1
      register: pubsub1_out

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        cidr: "{{PubSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub2
      register: pubsub2_out

    - name: Create Public Subnet 3
      ec2_vpc_subnet:
        cidr: "{{PubSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: pubsub3
      register: pubsub3_out

    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        cidr: "{{PrivSub1Cidr}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub1
      register: privsub1_out

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        cidr: "{{PrivSub2Cidr}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub2
      register: privsub2_out

    - name: Create Private Subnet 3
      ec2_vpc_subnet:
        cidr: "{{PrivSub3Cidr}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        map_public: yes
        wait: yes
        wait_timeout: 300
        tags:
          Name: privsub3
      register: privsub3_out

    - name: Create Internet GateWay
      ec2_vpc_igw:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        tags:
          Name: Vprofile-IGW
      register: igwout

    - name: Create IGW_RT
      ec2_vpc_route_table:
        region: "{{region}}"
        state: "{{state}}"
        vpc_id: "{{vpcout.vpc.id}}"
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igwout.gateway_id }}"
        tags:
          Name: IGW_RT




